<?php
if(!isset($_SESSION)){
    session_start();
}
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
</head>

<body>
<!-- MODAL DE SESSAO -->
<?php if(isset($_SESSION['username'])){ ?>
    <div id="modal-login" class="modal">
        <div class="modal-header">
            <span><?php echo $_SESSION['username']; ?>: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <h3>Oque deseja fazer?</h3>
            <a href="/usuarios/index">Configuraçõs de usuário.</a><br>
            <a href="/usuarios/logout">Sair.</a>
        </div>
    </div>
<?php }else{ ?>
    <div id="modal-login" class="modal">
        <div class="modal-header">
            <span>Login: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/retrieve" method="POST">
                <label class="modal-label">E-mail: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-envelope"></i></span>
                    <input type="text" name="email" placeholder="Digite seu E-mail aqui!" />
                </div>
                <label class="modal-label">Senha: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span>
                    <input type="password" name="senha" />
                </div>
                <a href="/usuarios/forgot">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
            </form>
        </div>
    </div>
<?php } ?>
<!-- MENU SUPERIOR -->
<div class="navbar">
    <img src="/images/cabecalho.png">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>
        </div>
    </div>
</div>
<div class="container">
    <div class="hero-unit">
        <h2 class="center">Um pouco dos criadores...</h2>
        <br>
        <p class="center">Veja a seguir um poco sobre os criadores do blog Controlinho</p>
    </div>
    <div class="row">
        <div class="span4 popover-title">
            <h3>Felippe Ribeiro dos Santos</h3>
            <img class="img-circle" src="images/user-avatar/santos.jpg"><br><br>
            <p class="center">Jovem garoto de 19 anos de idade, também conhecido como o cara do sobrenome complicado, ou pra quem tenta falar Subiski. Atualmente trabalha na empresa DimoTech soluções em software ltda. no cargo de programador web, a algo em torno de 1 ano na função. O mesmo juntamente com seus amigos teve a ideia do Controlinho a pouco tempo, e com esforço lança hoje (30/02/2015) o blog Controlinho na sua versão Alfa.</p>
            <br><br><br>
            <p class="center"><a target="_blank" class="btn btn-primary" href="https://www.facebook.com/felippe.omgt"><i class="icon-thumbs-up"></i> View details &raquo;</a></p>
        </div>
        <div class="span4 popover-title">
            <h3>Gabriel Avila da Silva</h3>
            <img class="img-circle" src="images/user-avatar/avila.jpg"><br><br>
            <p class="center">Jovem garoto de 19 anos de idade, também conhecido como o Terceiro melhor do melhor do mundo em bocha (que na verdade é bolão e não bocha), BochaMan ou bochero ou ainda simplesmente Avila. Atualmente trabalha na empresa DimoTech soluções em software ltda. no cargo de programador web, a algo em torno de 4 meses na função. O mesmo juntamente com seus amigos teve a ideia do Controlinho a pouco tempo, e com esforço lança hoje (30/02/2015) o blog Controlinho na sua versão Alfa.</p>
            <br>
            <p class="center"><a target="_blank" class="btn btn-primary" href="https://www.facebook.com/gabriel.avila.9849"><i class="icon-thumbs-up"></i> View details &raquo;</a></p>
        </div>
        <div class="span4 popover-title">
            <h3>Iuri Leonardo Bruski</h3>
            <img class="img-circle" src="images/user-avatar/bruski.jpg"><br><br>
            <p class="center">Jovem garoto de 18 anos de idade, também conhecido como o cara que não tem apelido nem nada. Atualmente trabalha na empresa CRS Centro de Residência em Software no cargo de programador web, a algo em torno de 4 meses na função. O mesmo juntamente com seus amigos teve a ideia do Controlinho a pouco tempo, e com esforço lança hoje (30/02/2015) o blog Controlinho na sua versão Alfa.</p>
            <br><br><br><br>
            <p class="center"><a target="_blank" class="btn btn-primary" href="https://www.facebook.com/iurileonardo.bruski?fref=ufi"><i class="icon-thumbs-up"></i> View details &raquo;</a></p>
        </div>
    </div>
</div>
    <footer class="lala">
        <div class="center">
            <p>Um oferecimento de Controlinho</p>
            <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
    </footer>

</div>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    function Cancel(){
        location.href="/";
    }
</script>
</body>
</html>