<?php
    if(!isset($_SESSION)){
    session_start();
    }
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
</head>

<body>
<!-- MODAL DE SESSAO -->
<?php if(isset($_SESSION['username'])){ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span><?php echo $_SESSION['username']; ?>: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
                <h3>Oque deseja fazer?</h3>
                <a href="/usuarios/index">Configuraçõs de usuário.</a><br>
                <a href="/usuarios/logout">Sair.</a>
        </div>
</div>
<?php }else{ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span>Login: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/retrieve" method="POST">
                <label class="modal-label">E-mail: </label>
                <input type="text" name="email" placeholder="Digite seu E-mail aqui!" />
                <label class="modal-label">Senha: </label>
                <input type="password" name="senha" />
                <a href="/usuarios/retrieve">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
                
            </form>
        </div>
</div>
<?php } ?>
<!-- MENU SUPERIOR -->
<div class="navbar">
    <img src="/images/cabecalho.png">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>
        </div>
    </div>
</div>
<!-- SIDEBAR -->
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <?php if(isset($_SESSION['username'])){ ?>
                    <img src="/images/user-avatar/<?php echo $_SESSION['avatar'] ?>">
                    <br>
                    <h4><?php echo $_SESSION['username']?></h4>
                <?php } else { ?>
                    <img src="/images/avatar.jpg">
                    <br>
                    <h4>Visitante</h4>
                <?php } ?>
                <br>
                <br>
                <form action="/save" method="POST">
                    <button type="submit" class="btn btn-primary">Criar post</button>
                </form>
            </div>
        </div>
        <div class="span9">
            <?php foreach($this->content as $content) {
                if ($content['status'] == '1') {
                    ?>
                    <div class="hero-unit">
                        <form action="/delete" method="POST">
                            <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                            <input type="submit" class="icon-remove icons" value="" >
                        </form>
                        <form action="/save" method="POST">
                            <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                            <input type="submit" class="icon-pencil icons" value="" >
                        </form>
                        <div class="popover-title">
                            <h3><strong><?php echo $content['titulo']; ?></strong></h3>
                            <h5>Postado por: <?php echo $content['nome']?></h5>
                        </div>
                        <hr>
                        <div class="popover-content">
                            <?php if (isset($content['media']) && isset($content['src'])) { ?>

                                <?php if ($content['src'] == 'img') { ?>
                                    <img style="height: 320px;" src="images/user-image/<?php echo $content['media'] ?>">
                                <?php } ?>
                                <?php if ($content['src'] == 'video') { ?>
                                    <iframe src="images/user-image/<?php echo $content['media'] ?>"></iframe>
                                <?php } ?>

                            <?php } ?>
                        </div>
                        <div class="popover-content center">
                            <?php $texto = explode(chr(10), $content['corpo']);
                            foreach ($texto as $paragrafo) {
                                ?>
                                <p><?php echo $paragrafo ?></p>
                            <?php } ?>
                        </div>
                        <form action="/comentario" method="POST">
                            <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                            <button type="submit" class="btn btn-primary">Comentar</button>
                        </form>
                        <?php foreach($this->comentario as $coment){
                            if($coment['post'] == $content['id']){ ?>
                                <div class="popover-title">
                                    <div class="row">
                                        <div style="margin-left: 30px;" class="span3"><h5><?php echo $coment['nome'] ?></h5></div>
                                        <div class="span6 popover-title"><p><?php echo $coment['comentario'] ?></p></div>
                                    </div>
                                </div>
                            <?php }
                        } ?>
                    </div>
                <?php }
            }?>
        </div>
    </div>
    <div class="pagination pagination-centered">
        <ul>
            <li><a href="/controlinho">Anterior</a></li>
            <li><a href="/controlinho/page/1">1</a></li>
            <li><a href="/controlinho/page/2">2</a></li>
            <li><a href="/controlinho/page/3">3</a></li>
            <li><a href="#">Próxima</a></li>
        </ul>
    </div>

    <footer class="lala">
        <div class="center">
            <p>Um oferecimento de Controlinho</p>
            <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
    </footer>

</div>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    window.onload="pagination()";
    function pagination() {
        $(selector).pagination({
            items: 100,
            itemsOnPage: 10
        });
    }
</script>
</body>
</html>