<?php
    if(!isset($_SESSION)){
    session_start();
    }
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
</head>

<body>
<!-- MENSAGENS DE ERROR -->
<?php if(isset($GLOBALS['sucess_email'])){
    echo '<div id="sucess-nome" class="alert alert-error">
<a href="" class="close pull-right" >x</a>';
    if($GLOBALS['sucess_email'] == 'error'){
        echo '<h4>Falha no envio do e-mail!</h4>';
    }
    if($GLOBALS['sucess_email'] == 'error_404'){
        echo '<h4>E-mail não cadastrado!</h4>';
    }
    echo '</div>';
} ?>
<!-- MENSAGENS DE SUCESSO -->
<?php if(isset($GLOBALS['success_post'])){
    echo '<div id="sucess-nome" class="alert alert-success">
<a href="" class="close pull-right" >x</a>';
    if($GLOBALS['success_auth'] == 'delete'){
        echo '<h4>Post deletado com sucesso!</h4>';
    }
    if($GLOBALS['success_auth'] == 'edit'){
        echo '<h4>Edição no post realizada com sucesso!</h4>';
    }
    if($GLOBALS['success_auth'] == 'creat'){
        echo '<h4>Post criado com sucesso!</h4>';
    }
    if($GLOBALS['success_auth'] == 'coment'){
        echo '<h4>Comentario realizado com sucesso!</h4>';
    }
    if($GLOBALS['sucess_email'] == 'sucess'){
        echo '<h4>E-mail enviado com sucesso, verifique a sua caixa de entrada!</h4>';
    }
    if($GLOBALS['succes'] == 'sucess'){
        echo '<h4>Usuário excluido com sucesso!</h4>';
    }
    if($GLOBALS['succes'] == 'sucess_add'){
        echo '<h4>Usuário cadastrado com sucesso!</h4>';
    }
    echo '</div>';
} ?>
<!-- MODAL DE SESSAO -->
<?php if(isset($_SESSION['username'])){ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span><?php echo $_SESSION['username']; ?>: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
                <h3>Oque deseja fazer?</h3>
                <?php if($_SESSION['status'] == 2){ ?> 
                <a href="/usuarios/admin">Configurações de administrador.</a><br>
                <a href="/usuarios/logout">Sair.</a>
                <?php }else{ ?>
                <a href="/usuarios/index">Configurações de usuário.</a><br>
                <a href="/usuarios/logout">Sair.</a>
                <?php } ?>
        </div>
</div>
<?php }else{ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span>Login: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/retrieve" method="POST">
                <label class="modal-label">E-mail: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-envelope"></i></span>
                    <input type="text" name="email" placeholder="Digite seu E-mail aqui!" />
                </div>
                <label class="modal-label">Senha: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span>
                    <input type="password" name="senha" />
                </div>
                <a href="/usuarios/retrieve">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
            </form>
        </div>
</div>
<?php } ?>
<!-- MENU SUPERIOR -->
<div class="navbar">
    <img src="/images/cabecalho.png">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>
        </div>
    </div>
</div>
<!-- SIDEBAR -->
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <?php if(isset($_SESSION['username'])){ ?>
                    <img src="/images/user-avatar/<?php echo $_SESSION['avatar'] ?>">
                    <br>
                    <h4><?php echo $_SESSION['username']?></h4>
                    <br>
                    <br>
                    <form action="/save" method="POST">
                        <button type="submit" class="btn btn-primary">Criar post</button>
                    </form>
                <?php } else { ?>
                    <img src="/images/avatar.jpg">
                    <br>
                    <h4>Visitante</h4>
                <?php } ?>
            </div>
        </div>
        <div class="span9">
            <?php foreach($this->content as $content) {
                if ($content['status'] == '1') {
                    ?>
                    <div class="hero-unit">
                        <?php if(isset($_SESSION)){

                        } elseif($_SESSION['status'] == 1 && $_SESSION['userid'] == $content['id']){ ?>
                            <form action="/save" method="POST">
                                <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                                <input type="submit" class="icon-pencil icons" value="" >
                            </form>
                        <?php } else { ?>
                            <form action="/delete" method="POST">
                                <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                                <input type="submit" class="icon-remove icons" value="" >
                            </form>
                            <form action="/save" method="POST">
                                <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                                <input type="submit" class="icon-pencil icons" value="" >
                            </form>
                        <?php } ?>
                        <div class="popover-title">
                            <h3><strong><?php echo $content['titulo']; ?></strong></h3>
                            <h5>Postado por: <?php echo $content['nome']?></h5>
                        </div>
                        <hr>
                        <div class="popover-content">
                            <?php if (isset($content['media']) && isset($content['src'])) { ?>

                                <?php if ($content['src'] == 'img') { ?>
                                    <img style="height: 320px;" src="images/user-image/<?php echo $content['media'] ?>">
                                <?php } ?>
                                <?php if ($content['src'] == 'video') { ?>
                                    <iframe src="images/user-image/<?php echo $content['media'] ?>"></iframe>
                                <?php } ?>

                            <?php } ?>
                        </div>
                        <div class="popover-content center">
                            <?php $texto = explode(chr(10), $content['corpo']);
                            foreach ($texto as $paragrafo) {
                                ?>
                                <p><?php echo $paragrafo ?></p>
                            <?php } ?>
                        </div>
                        <form action="/comentario" method="POST">
                            <input type="hidden" name="id" value="<?php echo $content['id'] ?>">
                            <button type="submit" class="btn btn-primary">Comentar</button>
                        </form>
                        <?php foreach($this->comentario as $coment){
                            if($coment['post'] == $content['id']){ ?>
                                <div class="popover-title">
                                    <div class="row">
                                        <div style="margin-left: 30px;" class="span3"><h5><?php echo $coment['nome'] ?></h5></div>
                                        <div class="span6 popover-title"><p><?php echo $coment['comentario'] ?></p></div>
                                    </div>
                                </div>
                            <?php }
                        } ?>
                    </div>
                <?php }
            }?>
        </div>
    </div>
    <div class="pagination pagination-centered">
        <ul>
            <li><a href="/controlinho">Anterior</a></li>
            <li><a href="/controlinho/page/1">1</a></li>
            <li><a href="/controlinho/page/2">2</a></li>
            <li><a href="/controlinho/page/3">3</a></li>
            <li><a href="#">Próxima</a></li>
        </ul>
    </div>

    <footer class="lala">
        <div class="center">
            <p>Um oferecimento de Controlinho</p>
            <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
    </footer>

</div>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    window.onload="pagination()";
    function pagination() {
        $(selector).pagination({
            items: 100,
            itemsOnPage: 10
        });
    }
</script>
</body>
</html>