<script>
    function AbrirLogin(){
        var login = document.getElementById('modal-login').style.display;
        if(login == 'none'){
            document.getElementById('modal-login').style.display = 'block';
        }else{
            document.getElementById('modal-login').style.display = 'none';
        }
    }
</script>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
</head>

<body>
<!-- MODAL DE LOGIN -->
<div id="modal-login" class="modal" style="display: none">
    <div class="modal-header">
        <span>Login: </span>
        <a href="" class="close" >X</a>
    </div>
    <div class="modal-body">
        <form action="/usuarios/login" method="POST">
            <label class="modal-label">E-mail: </label>
            <input type="text" name="email-login" placeholder="Digite seu E-mail aqui!" />
            <label class="modal-label">Senha: </label>
            <input type="password" name="senha-login" />
            <a href="/usuarios/retrieve">Esqueceu a senha?</a><br>
            <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
            <button class="btn-success" type="submit">Entrar</button>

        </form>
    </div>
</div>
<!-- MENU SUPERIOR -->
<div class="navbar">
    <img src="/images/cabecalho.png">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about/index"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#" onclick="AbrirLogin()"><img src="/images/buttons/botao_login.png"></a>
        </div>
    </div>
</div>
<!-- SIDEBAR -->
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <?php if(isset($_SESSION)){ ?>
                    <img src="/images/<?=$_SESSION['avatar']?>">
                    <br>
                    <h4><?= $_SESSION['username']?></h4>
                <?php } else { ?>
                    <img src="/images/avatar.jpg">
                    <br>
                    <h4>Visitante</h4>
                <?php } ?>
            </div>
        </div>
        <div class="span9">
            <?php foreach($this->content as $content) {
                if ($content['status'] == '1') {
                    ?>
                    <div class="hero-unit">
                        <div class="popover-title">
                            <h3><strong><?php echo $content['titulo']; ?></strong></h3><h5>Postado
                                por: <?php echo $content['nome']?></h5>
                        </div>
                        <hr>
                        <div class="popover-content">
                            <?php if (isset($content['media']) && isset($content['src'])) { ?>

                                <?php if ($content['src'] == 'img') { ?>
                                    <img style="height: 320px;" src="<?php echo $content['media'] ?>">
                                <?php } ?>
                                <?php if ($content['src'] == 'video') { ?>
                                    <iframe src="<?php echo $content['media'] ?>"></iframe>
                                <?php } ?>

                            <?php } ?>
                        </div>
                        <div class="popover-content center">
                            <?php $texto = explode(chr(10), $content['corpo']);
                            foreach ($texto as $paragrafo) {
                                ?>
                                <p><?php echo $paragrafo ?></p>
                            <?php } ?>
                        </div>
                    </div>

                <?php }
            }?>
        </div>
    </div>
    <div class="pagination pagination-centered">
        <ul>
            <li><a href="/controlinho">Anterior</a></li>
            <li><a href="/controlinho/page/1">1</a></li>
            <li><a href="/controlinho/page/2">2</a></li>
            <li><a href="/controlinho/page/3">3</a></li>
            <li><a href="#">Próxima</a></li>
        </ul>
    </div>

    <footer class="lala">
        <div class="center">
            <p>Um oferecimento de Controlinho</p>
            <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
    </footer>

</div>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    window.onload="pagination()";
    function pagination() {
        $(selector).pagination({
            items: 100,
            itemsOnPage: 10
        });
    });
</script>
</body>
</html>