<?php
    if(!isset($_SESSION)){
    session_start();
    }
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
</head>

<body>
<!-- MODAL DE SESSAO -->
<?php if(isset($_SESSION['username'])){ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span><?php echo $_SESSION['username']; ?>: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
                <h3>Oque deseja fazer?</h3>
                <a href="/usuarios/index">Configuraçõs de usuário.</a><br>
                <a href="/usuarios/logout">Sair.</a>
        </div>
</div>
<?php }else{ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span>Login: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/retrieve" method="POST">
                <label class="modal-label">E-mail: </label>
                <input type="text" name="email" placeholder="Digite seu E-mail aqui!" />
                <label class="modal-label">Senha: </label>
                <input type="password" name="senha" />
                <a href="/usuarios/retrieve">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
                
            </form>
        </div>
</div>
<?php } ?>
<!-- MENU SUPERIOR -->
<div class="navbar">
    <img src="/images/cabecalho.png">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>
        </div>
    </div>
</div>
<!-- SIDEBAR -->
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <?php if(isset($_SESSION['username'])){ ?>
                    <img src="/images/user-avatar/<?php echo $_SESSION['avatar'] ?>">
                    <br>
                    <h4><?php echo $_SESSION['username']?></h4>
                <?php } else { ?>
                    <img src="/images/avatar.jpg">
                    <br>
                    <h4>Visitante</h4>
                <?php } ?>
                <br>
                <br>
                <form action="/save" method="POST">
                    <button type="submit" class="btn btn-primary">Criar post</button>
                </form>
            </div>
        </div>
        <div class="span9">
            <div class="hero-unit">
                <div class="popover-title">
                    <h3>Criando novo post...</h3>
                </div>
                <br>
                <?php if(isset($this->content)){ ?>
                    <form action="/save" method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="<?php echo $this->content[0]['id'] ?>">
                        <span>Titulo</span><i class="icon-arrow-down icons"></i>
                        <input value="<?php echo $this->content[0]['titulo'] ?>" class="input-block-level" type="text" name="titulo" placeholder="Insira um titulo para seu post">
                        <br><br>
                        <span>Corpo</span><i class="icon-arrow-down icons"></i>
                        <textarea class="input-block-level" rows="3" name="corpo" placeholder="Escreva aqui seu post"><?php echo $this->content[0]['corpo'] ?></textarea>
                        <br>
                        <span>Tipo de Midia</span><i class="icon-arrow-down icons"></i><br>
                        <select value="<?php echo $this->content[0]['src'] ?>" class="span2" name="tipoMidia">
                            <?php if($this->content[0]['src'] == 'video' ){ ?>
                                <option value="">--------</option>
                                <option value="video" selected>Vídeo</option>
                                <option value="img">Imagem</option>
                            <?php } else { ?>
                                <option value="">--------</option>
                                <option value="video">Vídeo</option>
                                <option value="img" selected>Imagem</option>
                            <?php } ?>
                        </select>
                        <br><br>
                        <span>Midia</span><i class="icon-arrow-down icons"></i><br>
                        <input value="<?php echo $this->content[0]['media'] ?>" type="file" name="midia">
                        <div class="form-actions">
                            <button type="submit" class="btn btn-success">Salvar Post</button>
                            <button onclick="Cancel();" type="button" class="btn">Cancelar</button>
                        </div>
                    </form>
                <?php } else {?>
                    <form action="/save" method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="id">
                        <span>Titulo</span><i class="icon-arrow-down icons"></i>
                        <input class="input-block-level" type="text" name="titulo" placeholder="Insira um titulo para seu post">
                        <br><br>
                        <span>Corpo</span><i class="icon-arrow-down icons"></i>
                        <textarea class="input-block-level" rows="3" name="corpo" placeholder="Escreva aqui seu post"></textarea>
                        <br>
                        <span>Tipo de Midia</span><i class="icon-arrow-down icons"></i><br>
                        <select class="span2" name="tipoMidia">
                            <option value="">--------</option>
                            <option value="video">Vídeo</option>
                            <option value="img">Imagem</option>
                        </select>
                        <br><br>
                        <span>Midia</span><i class="icon-arrow-down icons"></i><br>
                        <input type="file" name="midia">
                        <div class="form-actions">
                            <button type="submit" class="btn btn-success">Salvar Post</button>
                            <button onclick="Cancel();" type="button" class="btn">Cancelar</button>
                        </div>
                    </form>
                <?php } ?>
            </div>
        </div>
    </div>

    <footer class="lala">
        <div class="center">
            <p>Um oferecimento de Controlinho</p>
            <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
    </footer>

</div>
<script>
    function Cancel(){
        location.href="/";
    }
</script>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
</body>
</html>