<?php
    if(!isset($_SESSION)){
    session_start();
    }
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
 	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
  </head>

  <body>
<!-- MODAL DE SESSAO -->
<?php if(isset($_SESSION['username'])){ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span><?php echo $_SESSION['username']; ?>: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
                <h3>Oque deseja fazer?</h3>
                <?php if($_SESSION['status'] == 2){ ?> 
                <a href="/usuarios/admin">Configurações de administrador.</a><br>
                <a href="/usuarios/logout">Sair.</a>
                <?php }else{ ?>
                <a href="/usuarios/index">Configurações de usuário.</a><br>
                <a href="/usuarios/logout">Sair.</a>
                <?php } ?>
        </div>
</div>
<?php }else{ ?>
<div id="modal-login" class="modal">
        <div class="modal-header">
            <span>Login: </span>
            <a href="#close" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/retrieve" method="POST">
                <label class="modal-label">E-mail: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-envelope"></i></span>
                    <input type="text" name="email" placeholder="Digite seu E-mail aqui!" />
                </div>
                <label class="modal-label">Senha: </label>
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span>
                    <input type="password" name="senha" />
                </div>
                <a href="/usuarios/forgot">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
            </form>
        </div>
</div>
<?php } ?>
<!-- MENU SUPERIOR -->
    <div class="navbar">
    	<img src="/images/cabecalho.png">
      	<div class="navbar-inner">
        	<div class="container-fluid">
            <a class="btn-first" href="/"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal" href="/about/index"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal" href="http://clickjogos.com.br"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>    
       		 </div>
      	</div>
    </div>
<!-- MENSAGENS DE ERRO -->
<?php if(isset($GLOBALS['error_auth'])){
echo '<div id="error-nome" class="alert alert-error">
    <a href="" class="close pull-right" >x</a>';
    if($GLOBALS['error_auth'] == 'nome'){
        echo '<h4>O campo nome não está correto, verifique!</h4>';
    }
    if($GLOBALS['error_auth'] == 'senha'){
        echo '<h4>O campo senha é necessário, verifique!</h4>';
    }
    if($GLOBALS['error_auth'] == 'email'){
        echo '<h4>O campo e-mail não está correto, verifique!</h4>';
    }
    if($GLOBALS['error_auth'] == 'email_existente'){
        echo '<h4>Email já cadastrado, verifique!</h4>';
    }
echo '</div>';
} ?>
        <div class="container">
            <div class="form-signin">
            <form action="" method="POST">
                  <h3> Recuperar Senha:</h3>
                  <label>E-mail: </label>
                  <input type="email" name="email" placeholder="exemplo@controlinho.com" />
                  <input type="submit" name="salvar" value="Enviar" class="btn-success btn-large" />
              </form>
            </div>
    </div>
 <footer class="lala">
        <div class="center">
          <p>Um oferecimento de Controlinho</p>
          <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
      </footer>

    <script src="../assets/js/bootstrap.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script>

  </body>
</html>