<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Controlinho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">

    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
 	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/images/favicon.jpg" >
  </head>

  <body>
<!-- MODAL DE LOGIN -->
<div id="modal-login" class="modal hidden">
        <div class="modal-header">
            <span>Login: </span>
            <a href="" class="close" >X</a>
        </div>
        <div class="modal-body">
            <form action="/usuarios/login" method="POST">
                <label class="modal-label">E-mail: </label>
                <input type="text" name="email-login" placeholder="Digite seu E-mail aqui!" />
                <label class="modal-label">Senha: </label>
                <input type="password" name="senha-login" />
                <a href="/usuarios/retrieve">Esqueceu a senha?</a><br>
                <a href="/usuarios/save">Quer fazer um novo cadastro?</a><br><br>
                <button class="btn-success" type="submit">Entrar</button>
                
            </form>
        </div>
</div>
<!-- MENU SUPERIOR -->
    <div class="navbar">
    	<img src="/images/cabecalho.png">
      	<div class="navbar-inner">
        	<div class="container-fluid">
            <a class="btn-first"><img src="/images/buttons/botao_home.png"></a>
            <a class="btn-normal"><img src="/images/buttons/botao_about.png"></a>
            <a class="btn-normal"><img src="/images/buttons/botao_arcade.png"></a>
            <a class="btn-login" href="#modal-login"><img src="/images/buttons/botao_login.png"></a>
       		 </div>
      	</div>
    </div>
<!-- MENSAGENS DE ERRO -->
<div id="error-nome" class="alert alert-error none">
    <a href="" class="close pull-right" >x</a>
    <h4>O campo nome não está correto, verifique!</h4>
</div>
<div id="error-email" class="alert alert-error none">
    <a href="" class="close pull-right" >x</a>
    <h4>O campo e-mail não está correto, verifique!</h4>
</div>
        <div class="container">
            <div class="form-signin">
            <form action="" method="POST">
                  <h3> Novo Usuário:</h3>
                  <label>Nome: </label>
                  <input type="text" name="nome" placeholder="Digite seu nome aqui!" />
                  <label>E-mail: </label>
                  <input type="email" name="email" placeholder="exemplo@controlinho.com" />
                  <label>Senha: </label>
                  <input type="password" name="senha" /><br>
                  <input type="submit" name="salvar" value="Enviar" class="btn-success btn-large" />
              </form>
            </div>
    </div>
 <footer class="lala">
        <div class="center">
          <p>Um oferecimento de Controlinho</p>
          <p>&copy; 2015 - Felippe, Gabriel e Iuri</p>
        </div>
      </footer>

    <script src="../assets/js/bootstrap.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script>

  </body>
</html>